[package]
name = "frontend"
version = "0.1.0"
authors = ["Peter Njeim <peterthegreatpeterthegreat@hotmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.67"
yew = "0.18.0"
