[package]
name = "frontend"
version = "0.1.0"
authors = ["Peter Njeim <peterthegreatpeterthegreat@hotmail.com>"]
edition = "2018"

[dependencies]
yew = "0.18"
petgraph = "0.5"
material-yew = { version = "0.1", features = ["full"] }
tournament = { path = "../tournament" }
