[package]
name = "frontend"
version = "0.1.1"
authors = ["Peter Njeim <peterthegreatpeterthegreat@hotmail.com>"]
edition = "2021"

[dependencies]
yew = "0.18"
petgraph = "0"
material-yew = { version = "0", features = ["full"] }
tournament = { path = "../tournament" }
