[package]
name = "backend"
version = "0.1.0"
authors = ["Peter Njeim <peterthegreatpeterthegreat@hotmail.com>"]
edition = "2021"

[dependencies]
actix-web = "4.0.0-beta.8"
actix-files = "0.6.0-beta.6"
