[package]
name = "tournament"
version = "0.1.1"
authors = ["Peter Njeim <peterthegreatpeterthegreat@hotmail.com>"]
edition = "2021"

[dependencies]
criterion = "0"
petgraph = "0"
rayon = "1"

[[bench]]
name = "triangle_benchmark"
harness = false
