[package]
name = "tournament"
version = "0.1.0"
authors = ["Peter Njeim <peterthegreatpeterthegreat@hotmail.com>"]
edition = "2018"

[dependencies]
criterion = "0.3.4"
petgraph = "0.5.1"
rayon = "1.5.1"

[[bench]]
name = "triangle_benchmark"
harness = false
